# Generated by Django 5.1.4 on 2025-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Architecture', 'Architecture'), ('Structural', 'Structural'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Quantity Surveying', 'Quantity Surveying')], max_length=100)),
                ('image', models.ImageField(upload_to='past_work/')),
            ],
        ),
    ]
